name: 🏠 Build

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    name: 🏠 Build
    steps:
      - name: 🧹 Cancel previus redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
          
      - name: 👍 Checkout
        uses: actions/checkout@v2
      
      - name: ⚙️ Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: 📥 Install Dependencies
        run: npm ci

      - name: 🏠 Build
        run: npm run build
        
      - name: 💅 Lint
        run: npm run lint

      - name: 💇‍♀️ Lint --fix
        run: npm run lint:fix

      - name: ✅ Test
        run: npm run test
